name: lapormin
description: 'Aplikasi pelaporan masyarakat'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^7.1.1
  bloc: ^9.2.1
  dartz: ^0.10.1
  dotted_border: ^3.1.0
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.1
  flutter_map: ^8.3.0
  flutter_otp_text_field: ^1.5.1+1
  flutter_svg: ^2.3.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_it: ^9.2.1
  image_picker: ^1.2.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  lottie: ^3.3.3
  page_transition: ^2.2.1
  path: ^1.9.1
  shared_preferences: ^2.5.5
  shimmer: ^3.0.0
  supabase_flutter: ^2.12.4
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/profiles/
    - assets/images/cards/
    - assets/animations/

  # example:
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Regular.ttf
        - asset: assets/fonts/DM_Sans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DM_Sans/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DM_Sans/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DM_Sans/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DM_Sans/DMSans-Black.ttf
          weight: 900
