// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1qkNfUKJuIwJlLiIwPaM7V442Dy38ys0',
    appId: '1:810088677139:web:14a117be650371dae764e6',
    messagingSenderId: '810088677139',
    projectId: 'lapormin-4b0a9',
    authDomain: 'lapormin-4b0a9.firebaseapp.com',
    storageBucket: 'lapormin-4b0a9.firebasestorage.app',
    measurementId: 'G-WTGJFNY6YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANRuovd7fc1UdT7Us-t7sSztZZ32rrDKk',
    appId: '1:810088677139:android:88293c597d4fb346e764e6',
    messagingSenderId: '810088677139',
    projectId: 'lapormin-4b0a9',
    storageBucket: 'lapormin-4b0a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAMz-lutHGrGdPaJ8T9ubcLeJkC86g8DE',
    appId: '1:810088677139:ios:fd6badf867db2cf7e764e6',
    messagingSenderId: '810088677139',
    projectId: 'lapormin-4b0a9',
    storageBucket: 'lapormin-4b0a9.firebasestorage.app',
    iosBundleId: 'com.unggulan.lapormin',
  );
}
